import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from "@/lib/authContext";

export const metadata: Metadata = {
  title: "Sistema predictido",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={` antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
